<?php

/**
 * @file
 * Install, update and uninstall hooks for dcycle.
 */

/**
 * Implements hook_uninstall().
 */
function dcycle_uninstall() {
  variable_del('dcycle_deployment_module');
  variable_del('dcycle_environment_type');
  variable_del('dcycle_version');
  variable_del('dcycle_site_id');
  variable_del('dcycle_policy');
  variable_del('dcycle_mockable_modules_list');
  variable_del('dcycle_mockable_base_type');
  variable_del('dcycle_mockable_base_more');
}
